training_sentences = [

    # ====================
    # ANXIETY (35 samples)
    # ====================
    "I feel nervous about my exams",
    "I am worried about my future",
    "I feel anxious and tense",
    "I cannot stop overthinking",
    "My heart races when I think about work",
    "I feel stressed about deadlines",
    "I am afraid I might fail",
    "I feel panic before presentations",
    "I constantly worry about small things",
    "I feel restless and uneasy",
    "I feel anxious about exams",
    "I am scared something will go wrong",
    "I feel pressure building up inside",
    "I cannot relax at all",
    "I feel overwhelmed with responsibilities",
    "What if everything goes wrong",
    "I'm so stressed I can't think straight",
    "I keep worrying about what people think",
    "My mind won't stop racing",
    "I feel on edge all the time",
    "I'm afraid of making mistakes",
    "The uncertainty is killing me",
    "I feel like I'm going to have a panic attack",
    "I can't shake this feeling of dread",
    "Everything feels too much right now",
    "I'm worried I'm not good enough",
    "What if I disappoint everyone",
    "I feel trapped by my thoughts",
    "The future scares me so much",
    "I'm constantly on high alert",
    "I have so much anxiety right now",
    "I'm terrified of what might happen",
    "My chest feels tight with worry",
    "I can't stop these anxious thoughts",
    "I feel like something bad will happen",

    # ====================
    # SADNESS (35 samples)
    # ====================
    "I feel sad today",
    "I feel empty inside",
    "Nothing makes me happy anymore",
    "I feel hopeless about life",
    "I feel lonely and isolated",
    "I feel down and tired",
    "I don't enjoy things anymore",
    "I feel like crying",
    "I feel emotionally drained",
    "Everything feels meaningless",
    "I feel hurt by what happened",
    "I feel disappointed in myself",
    "I feel abandoned and alone",
    "I feel broken inside",
    "I feel depressed and low",
    "I just want to stay in bed all day",
    "No one understands what I'm going through",
    "I feel like I'm carrying a heavy weight",
    "The sadness won't go away",
    "I miss how things used to be",
    "I feel so disconnected from everything",
    "Life feels colorless and grey",
    "I don't see the point anymore",
    "I feel numb to everything",
    "The loneliness is overwhelming",
    "I feel like I've lost myself",
    "Nothing brings me joy these days",
    "I feel unlovable and unwanted",
    "The pain won't stop",
    "I feel so tired of everything",
    "My heart feels heavy",
    "I'm grieving and it hurts so much",
    "I feel defeated by life",
    "Everything reminds me of my loss",
    "I can't stop feeling this sadness",

    # ====================
    # ANGER (30 samples)
    # ====================
    "I'm so angry right now",
    "This is completely unfair",
    "I can't believe they did this to me",
    "I feel so frustrated and mad",
    "Why does this always happen to me",
    "I'm fed up with everything",
    "This makes me furious",
    "I'm sick and tired of this",
    "How dare they treat me like this",
    "I feel rage inside",
    "This is infuriating",
    "I'm at my breaking point",
    "I can't take this anymore",
    "They have no right to do this",
    "I'm so irritated I could scream",
    "This situation is outrageous",
    "I feel disrespected and angry",
    "I'm tired of being treated badly",
    "This pisses me off so much",
    "I'm done with their nonsense",
    "I feel betrayed and angry",
    "Why won't they listen to me",
    "I'm angry at myself for this",
    "This is making my blood boil",
    "I feel hostile and defensive",
    "I hate how this makes me feel",
    "I'm furious about what happened",
    "They crossed the line this time",
    "I'm so resentful right now",
    "This anger is consuming me",

    # ====================
    # FEAR (25 samples) - NEW
    # ====================
    "I'm terrified of what might happen",
    "I feel scared and vulnerable",
    "Something terrible is going to happen",
    "I'm afraid I can't handle this",
    "Fear is paralyzing me right now",
    "I'm frightened by these thoughts",
    "What if I lose everything",
    "I'm scared of the unknown",
    "The fear won't let me move forward",
    "I feel threatened and unsafe",
    "I'm afraid to take the next step",
    "Fear is controlling my decisions",
    "I'm terrified of failing",
    "What if something bad happens to me",
    "I feel like I'm in danger",
    "I'm scared I'll be rejected",
    "The fear of judgment stops me",
    "I'm afraid of being alone",
    "I fear I'm not capable",
    "What if I can't recover from this",
    "I'm petrified of making a mistake",
    "Fear keeps me from trying",
    "I'm scared of losing control",
    "The future terrifies me",
    "I'm afraid no one will understand",

    # ====================
    # GUILT (20 samples) - NEW
    # ====================
    "I feel so guilty about what I did",
    "I can't stop feeling guilty",
    "It's all my fault this happened",
    "I should have done better",
    "I feel terrible for hurting them",
    "The guilt is eating me alive",
    "I keep blaming myself for everything",
    "I feel guilty for feeling this way",
    "I should have known better",
    "I can't forgive myself for this",
    "The guilt won't leave me alone",
    "I feel responsible for their pain",
    "I should have been there for them",
    "I feel bad for being selfish",
    "The weight of guilt is crushing",
    "I regret my actions so much",
    "I feel guilty for not doing enough",
    "I should have tried harder",
    "I can't shake this guilty feeling",
    "I blame myself for everything wrong",

    # ====================
    # SHAME (15 samples) - NEW
    # ====================
    "I feel so ashamed of myself",
    "I'm embarrassed by who I am",
    "I feel like such a failure",
    "Shame overwhelms me constantly",
    "I'm disgusted with myself",
    "I feel humiliated and small",
    "I'm ashamed of my behavior",
    "I feel unworthy and defective",
    "The shame is unbearable",
    "I hate myself for this",
    "I feel exposed and vulnerable",
    "I'm ashamed to show my face",
    "I feel like I'm not good enough",
    "The shame makes me want to hide",
    "I'm mortified by my mistakes",

    # ====================
    # POSITIVE (30 samples)
    # ====================
    "I feel happy today",
    "I feel confident about my skills",
    "I am proud of myself",
    "I feel excited about my project",
    "I feel motivated to work",
    "I feel optimistic about the future",
    "I feel calm and relaxed",
    "I achieved my goal",
    "I feel energetic and strong",
    "I am grateful for today",
    "I feel joyful and satisfied",
    "I feel inspired and hopeful",
    "I feel peaceful right now",
    "I feel proud of my progress",
    "I feel enthusiastic about learning",
    "Things are going really well",
    "I feel blessed and thankful",
    "I'm in such a good mood",
    "Life is beautiful right now",
    "I feel content and at peace",
    "I'm excited about the possibilities",
    "I feel alive and vibrant",
    "Everything is coming together nicely",
    "I feel confident in myself",
    "Today was such a good day",
    "I'm proud of how far I've come",
    "I feel hopeful about tomorrow",
    "Good things are happening",
    "I'm feeling really positive",
    "I have so much to be grateful for"
]


training_labels = [
    # Anxiety (35)
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",
    "anxiety","anxiety","anxiety","anxiety","anxiety",

    # Sadness (35)
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",
    "sadness","sadness","sadness","sadness","sadness",

    # Anger (30)
    "anger","anger","anger","anger","anger",
    "anger","anger","anger","anger","anger",
    "anger","anger","anger","anger","anger",
    "anger","anger","anger","anger","anger",
    "anger","anger","anger","anger","anger",
    "anger","anger","anger","anger","anger",

    # Fear (25)
    "fear","fear","fear","fear","fear",
    "fear","fear","fear","fear","fear",
    "fear","fear","fear","fear","fear",
    "fear","fear","fear","fear","fear",
    "fear","fear","fear","fear","fear",

    # Guilt (20)
    "guilt","guilt","guilt","guilt","guilt",
    "guilt","guilt","guilt","guilt","guilt",
    "guilt","guilt","guilt","guilt","guilt",
    "guilt","guilt","guilt","guilt","guilt",

    # Shame (15)
    "shame","shame","shame","shame","shame",
    "shame","shame","shame","shame","shame",
    "shame","shame","shame","shame","shame",

    # Positive (30)
    "positive","positive","positive","positive","positive",
    "positive","positive","positive","positive","positive",
    "positive","positive","positive","positive","positive",
    "positive","positive","positive","positive","positive",
    "positive","positive","positive","positive","positive",
    "positive","positive","positive","positive","positive"
]
